# Generated by Django 3.2 on 2025-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=200)),
                ('author_text', models.CharField(max_length=200)),
                ('sentiment', models.CharField(choices=[('-1', 'Negative'), ('1', 'Positive'), ('0', 'Neutral')], default='0', max_length=8)),
                ('create_date', models.DateTimeField(verbose_name='created at')),
                ('source', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(choices=[('1', 'Tweet'), ('2', 'Article'), ('3', 'Podcast'), ('4', 'Not Specfied')], default='4', max_length=20)),
                ('url', models.URLField()),
                ('title_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='published at')),
            ],
        ),
    ]
